package gui;

import java.io.RandomAccessFile;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * The debug gui for the Deck Injector.
 * @author Ryan Russell
 */
public class testGui extends javax.swing.JFrame {

    final boolean debug = true;
    final String gameDir = "F:\\Play\\Magic\\Game\\Magic\\";
    final String duelDir = "F:\\Play\\Magic\\Game\\Magic\\Playdeck\\";
    final String duel = "MyDeck.dck";
    final String game = "MAGIC4.SVE";
    final String nl = System.getProperty("line.separator");
    final int deckStart = Integer.parseInt("1420", 16);
    final static allCards cardMap = new allCards();
    RandomAccessFile duelFile;
    RandomAccessFile gameFile;
    String openGameFile = gameDir + game;
    String openDuelFile = duelDir + duel;
    gameDeck gameDeck = new gameDeck();
    duelDeck duelDeck = new duelDeck();
    
/**
 * Netbeans generated constructor.
 */
    public testGui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        duelDeckBox = new javax.swing.JTextArea();
        btnReadGame = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gameDeckBox = new javax.swing.JTextArea();
        txtBaseCard = new javax.swing.JTextField();
        btnWriteToFiles = new javax.swing.JButton();
        btnLoop = new javax.swing.JButton();
        btnReadDuel = new javax.swing.JButton();
        btnReadAllFiles = new javax.swing.JButton();
        statusBar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInject = new javax.swing.JButton();
        lblDuelName = new javax.swing.JLabel();
        lblGameName = new javax.swing.JLabel();
        txtIterations = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuTitleFile1 = new javax.swing.JMenu();
        menuOpenDuel = new javax.swing.JMenuItem();
        menuOpenGame = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        duelDeckBox.setColumns(20);
        duelDeckBox.setLineWrap(true);
        duelDeckBox.setRows(5);
        duelDeckBox.setText(" -Open a .dck file-");
        jScrollPane1.setViewportView(duelDeckBox);

        btnReadGame.setText("Read Game");
        btnReadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadGameActionPerformed(evt);
            }
        });

        gameDeckBox.setColumns(20);
        gameDeckBox.setLineWrap(true);
        gameDeckBox.setRows(5);
        gameDeckBox.setText(" -Open a .SVE file-");
        jScrollPane2.setViewportView(gameDeckBox);

        txtBaseCard.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtBaseCard.setText("00 00 00 00");
        txtBaseCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseCardActionPerformed(evt);
            }
        });

        btnWriteToFiles.setText("Write To Files");
        btnWriteToFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteToFilesActionPerformed(evt);
            }
        });

        btnLoop.setText("Write Loop");
        btnLoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoopActionPerformed(evt);
            }
        });

        btnReadDuel.setText("Read Duel");
        btnReadDuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadDuelActionPerformed(evt);
            }
        });

        btnReadAllFiles.setText("Read All Files");
        btnReadAllFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadAllFilesActionPerformed(evt);
            }
        });

        statusBar.setBackground(new java.awt.Color(220, 220, 220));
        statusBar.setText("Welcome to the Shandalar Deck Injector by RyanfaeScotland.");
        statusBar.setOpaque(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shandalar Deck:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Duel Deck:");

        btnInject.setText("Inject!");
        btnInject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInjectActionPerformed(evt);
            }
        });

        lblDuelName.setText("None");

        lblGameName.setText("None");

        txtIterations.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtIterations.setText("01");
        txtIterations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIterationsActionPerformed(evt);
            }
        });

        jLabel3.setText("Base Card:");

        jLabel4.setText("Iterations:");

        btnClear.setText("Clear Deck");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        menuTitleFile1.setText("File");

        menuOpenDuel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuOpenDuel.setText("Open Duel Deck");
        menuOpenDuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenDuelActionPerformed(evt);
            }
        });
        menuTitleFile1.add(menuOpenDuel);

        menuOpenGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuOpenGame.setText("Open Shandalar Deck");
        menuOpenGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenGameActionPerformed(evt);
            }
        });
        menuTitleFile1.add(menuOpenGame);

        jMenuBar2.add(menuTitleFile1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(btnReadDuel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(btnReadGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(btnReadAllFiles, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(btnWriteToFiles, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(btnLoop, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIterations, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBaseCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDuelName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGameName))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblGameName)
                    .addComponent(jLabel2)
                    .addComponent(lblDuelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnReadGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReadDuel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReadAllFiles)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBaseCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWriteToFiles)
                        .addGap(150, 150, 150)
                        .addComponent(btnClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnInject)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Pressing the Read Game button reads the cards from the currently open
 * save file. If there hasn't been a file opened then the default is used.
 * If there has been a file opened but is now closed it is then opened again.
 * @param evt
 */
private void btnReadGameActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        if (gameFile == null) {
            gameFile = new RandomAccessFile(openGameFile, "r");
        }
        if (!gameFile.getChannel().isOpen()) {
            gameFile = new RandomAccessFile(openGameFile, "r");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    String[] name = openGameFile.split("\\\\");
    lblGameName.setText(name[name.length-1]);
    gameDeck = getGameDeck();
    gameDeckBox.setText(gameDeck.toString(debug));
    try {
        gameFile = null;
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
}                                           
/**
 * The Write To Files button takes the code entered in the text box
 * and writes it to all the save files, 4 times for each file. Each 
 * time it is written it increases the left most bit by 1.
 * @param evt
 */
private void btnWriteToFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteToFilesActionPerformed
    //we don't need to check for files here as this is for adding cards to
    //all the files and is taken care of in the setDeckMultiFile method
    byte[] baseCard = new byte[4];
    String baseCardString = txtBaseCard.getText();
    String[] baseCardArray = baseCardString.split(" ");
    for (int i = 0; i < baseCard.length; ++i) {
        baseCard[i] = (byte) Integer.parseInt(baseCardArray[i], 16);
    }
    setDeckMultiFile(baseCard);
}//GEN-LAST:event_btnWriteToFilesActionPerformed

private void btnLoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoopActionPerformed
    // put 4 bytes in the textbox then loop round writing them to the
    // same file increasing by 1 each time
    try {
            gameFile = new RandomAccessFile(openGameFile, "rw");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    String[] name = openGameFile.split("\\\\");
    lblGameName.setText(name[name.length-1]);
    byte[] baseCard = new byte[4];
    String baseCardString = txtBaseCard.getText();
    String[] baseCardArray = baseCardString.split(" ");
    for (int i = 0; i < baseCard.length; ++i) {
        baseCard[i] = (byte) Integer.parseInt(baseCardArray[i], 16);
        }
    setDeckLoop(baseCard, Integer.parseInt(txtIterations.getText()));
    try {
        gameFile = null;
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
}//GEN-LAST:event_btnLoopActionPerformed

private void btnReadDuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadDuelActionPerformed
    try {
        if (duelFile == null) {
            duelFile = new RandomAccessFile(openDuelFile, "r");
        }
        if (!duelFile.getChannel().isOpen()) {
            duelFile = new RandomAccessFile(openDuelFile, "r");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    String[] name = openDuelFile.split("\\\\");
    lblDuelName.setText(name[name.length-1]);
    duelDeck = getDuelDeck();
    duelDeckBox.setText(duelDeck.toString(debug));
    try{
        duelFile = null;
    }catch (Exception e){
        JOptionPane.showMessageDialog(this, e);
    }
}//GEN-LAST:event_btnReadDuelActionPerformed

private void txtBaseCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseCardActionPerformed
}//GEN-LAST:event_txtBaseCardActionPerformed

private void btnReadAllFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadAllFilesActionPerformed
    String localDir = "F:\\Play\\Magic\\Game\\Magic\\";
    String localFile = "MAGIC";
    String extension = ".SVE";
    gameDeckBox.setText("");
    try {
        for (int x = 3; x <= 13; ++x) {
            gameFile = new RandomAccessFile(localDir + localFile + Hex(x).replaceFirst("0", "").toLowerCase() + extension, "rw");
            gameDeck currentDeck = getGameDeck();
            gameDeckBox.append("MAGIC" + Hex(x).replaceFirst("0", "").toLowerCase() + extension + " contains:" + nl + currentDeck.toString(debug));
            gameFile = null;
        }
    } catch (Exception e) {
    }
}//GEN-LAST:event_btnReadAllFilesActionPerformed

private void menuOpenGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenGameActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser = new JFileChooser(gameDir);
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Shandalar save files (.SVE)", "SVE");
    fileChooser.setFileFilter(filter);
    int returnValue = fileChooser.showOpenDialog(this);
    switch (returnValue) {
        case JFileChooser.APPROVE_OPTION:
            try {
                gameFile = new RandomAccessFile(fileChooser.getSelectedFile(), "r");
                openGameFile = fileChooser.getSelectedFile().getPath();
                String[] name = openGameFile.split("\\\\");
                lblGameName.setText(name[name.length-1]);
                gameDeckBox.setText("");
                gameDeck = getGameDeck();
                gameDeckBox.setText(gameDeck.toString(debug));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            break;
        case JFileChooser.CANCEL_OPTION:
            return;
        case JFileChooser.ERROR_OPTION:
            return;
    }  
    gameFile = null;
}//GEN-LAST:event_menuOpenGameActionPerformed

private void menuOpenDuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenDuelActionPerformed
// TODO add your handling code here:private void menuOpenDuelActionPerformed(java.awt.event.ActionEvent evt) {                                         
    //Open Duel deck
    JFileChooser fileChooser = new JFileChooser();
    fileChooser = new JFileChooser(duelDir);
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Duel deck files (.dck)", "dck");
    fileChooser.setFileFilter(filter);
    int returnValue = fileChooser.showOpenDialog(this);
    switch (returnValue) {
        case JFileChooser.APPROVE_OPTION:
            try {
                duelFile = new RandomAccessFile(fileChooser.getSelectedFile(), "r");
                openDuelFile = fileChooser.getSelectedFile().getPath();
                String[] name = openDuelFile.split("\\\\");
                lblDuelName.setText(name[name.length-1]);     
                duelDeckBox.setText("");
                duelDeck = getDuelDeck();
                duelDeckBox.append(duelDeck.toString(debug));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            break;
        case JFileChooser.CANCEL_OPTION:
            return;
        case JFileChooser.ERROR_OPTION:
            return;
    }
    duelFile = null;
}//GEN-LAST:event_menuOpenDuelActionPerformed

private void btnInjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInjectActionPerformed
    try {
        if (gameFile == null) {
            gameFile = new RandomAccessFile(openGameFile, "rw");
        }
        if (!gameFile.getChannel().isOpen()) {
            gameFile = new RandomAccessFile(openGameFile, "rw");
        }
        if (duelFile == null) {
                duelFile = new RandomAccessFile(openDuelFile, "r");
            }
        if (!duelFile.getChannel().isOpen()) {
                duelFile = new RandomAccessFile(openDuelFile, "r");
            }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    if (duelDeck.isEmpty()) {
        duelDeck = getDuelDeck();
    }
    gameDeck inject = duelDeck.convert(cardMap);
    System.out.println("Injecting: " + inject.toString(debug));
    injectToGame(inject);
    try {
        gameFile = null;
        duelFile = null;
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
}//GEN-LAST:event_btnInjectActionPerformed

private void txtIterationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIterationsActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtIterationsActionPerformed

private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    try {
        if (gameFile == null) {
            gameFile = new RandomAccessFile(openGameFile, "rw");
        }
        if (!gameFile.getChannel().isOpen()) {
            gameFile = new RandomAccessFile(openGameFile, "rw");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    String[] name = openGameFile.split("\\\\");
    lblGameName.setText(name[name.length-1]);
    clearDeck();
}//GEN-LAST:event_btnClearActionPerformed

    public String Hex(int in) {
        //Convert int to Hex String
        String value = Integer.toHexString(in).toUpperCase();
        if (value.equals("FFFFFFFF")) {
            value = "FF";
        }
        if (value.length() == 1) {
            value = "0" + value;
        }
        if (value.length() == 8) {
            char[] Bits = {value.charAt(6), value.charAt(7)};
            value = String.valueOf(Bits);
        }
        return value;
    }

    public String Hex(byte in) {
        //Convert byte to Hex String
        String value = Integer.toHexString(in).toUpperCase();
        if (value.equals("FFFFFFFF")) {
            value = "FF";
        }
        if (value.length() == 1) {
            value = "0" + value;
        }
        if (value.length() == 8) {
            char[] Bits = {value.charAt(6), value.charAt(7)};
            value = String.valueOf(Bits);
        }
        return value;
    }
    
    public String Hex(char in) {
//return a String Hex value from a char
        String value = Integer.toHexString(in).toUpperCase();
        if (value.equals("FFFFFFFF")) {
            value = "FF";
        }
        if (value.length() == 1) {
            value = "0" + value;
        }
            if (value.length() == 8) {
            char[] Bits = {value.charAt(6), value.charAt(7)};
            value = String.valueOf(Bits);
        }

        return value;
    }
           
    public void setDeckLoop(byte[] baseCard, int iterations){
    // sets the deck to whatever is in the textbox then with the first byte being
    // the startAmount and increasing to endAmount by 1 byte at a time and writing
    // the new card each time. So we can write a range from 00-FF by stating startAmount
    // as 00 and endAmount as FF then control the deck the cards go into with the textbox.
        try{
        byte[] newCardByte = baseCard;
        gameFile.seek(deckStart);
        for (int i = 0 ; i < iterations ; ++i) {
            newCardByte[0] = (byte) (newCardByte[0] + 1);
            gameFile.write(newCardByte);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }
    
    public void setDeckMultiFile(byte[] baseCard){
    // sets the card at offset to whatever is in the textbox for MAGIC3.SAV
    // then increases base card by 1 and writes to the next magic duelFile, looping
    // until MAGICd.SAV (MAGIC13.SAV). For each file 4 cards are written, one in each
    // deck one hand
        String localDir = "F:/Play/Magic/Game/Magic/";
        String localFile = "MAGIC";
        String extension = ".SVE";
        byte[] newCardByte = baseCard;        
        try {
            for (byte x = 3 ; x <= 13 ; ++x) {
        gameFile = new RandomAccessFile(localDir + localFile + Hex(x).replaceFirst("0", "").toLowerCase() + extension, "rw");
        gameFile.seek(deckStart);
        gameFile.write(newCardByte);//this card is in the hand
        ++newCardByte[0];
        newCardByte[2] = (byte) 1;  //this card is in deck 1
        gameFile.write(newCardByte);
        ++newCardByte[0];
        newCardByte[2] = (byte) 2;  //this card is in deck 2
        gameFile.write(newCardByte);
        ++newCardByte[0];
        newCardByte[2] = (byte) 4;  //this card is in deck 3
        gameFile.write(newCardByte);
        ++newCardByte[0];
        newCardByte[2] = (byte) 0;  //set us back to in hand
        for (int i = 0;i<251;++i){
        gameFile.write((byte)255);
        }
        gameFile = null;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }
    
    public String duelToName(int inCard){
        return switch (inCard) {
            case 0 -> "Air Elemental";
            case 1 -> "Ancestral Recall";
            case 2 -> "Animate Artifact";
            case 3 -> "Animate Dead";
            case 4 -> "Animate Wall";
            case 5 -> "Ankh of Mishra";
            case 6 -> "Armageddon";
            case 7 -> "Aspect of Wolf";
            case 8 -> "Bad Moon";
            case 9 -> "Badlands";
            case 10 -> "Balance";
            case 11 -> "Basalt Monolith";
            case 12 -> "Bayou";
            case 13 -> "Benalish Hero";
            case 14 -> "Berserk";
            case 15 -> "Birds of Paradise";
            case 16 -> "Black Knight";
            case 17 -> "Black Lotus";
            case 18 -> "Black Vise";
            case 19 -> "Black Ward";
            case 20 -> "Blaze of Glory";
            case 21 -> "Blessing";
            case 22 -> "Blue Elemental Blast";
            case 23 -> "Blue Ward";
            case 24 -> "Bog Wraith";
            case 25 -> "Braingeyser";
            case 26 -> "Burrowing";
            case 27 -> "Camouflage";
            case 28 -> "Castle";
            case 29 -> "Celestial Prism";
            case 30 -> "Channel";
            case 31 -> "Chaos Orb";
            case 32 -> "Chaoslace";
            case 33 -> "Circle of Protection: Black";
            case 34 -> "Circle of Protection: Blue";
            case 35 -> "Circle of Protection: Green";
            case 36 -> "Circle of Protection: Red";
            case 37 -> "Circle of Protection: White";
            case 38 -> "Clockwork Beast";
            case 39 -> "Clone";
            case 40 -> "Cockatrice";
            case 41 -> "Consecrate Land";
            case 42 -> "Conservator";
            case 43 -> "Contract from Below";
            case 44 -> "Control Magic";
            case 45 -> "Conversion";
            case 46 -> "Copper Tablet";
            case 47 -> "Copy Artifact";
            case 48 -> "Counterspell";
            case 49 -> "Craw Wurm";
            case 50 -> "Creature Bond";
            case 51 -> "Crusade";
            case 52 -> "Crystal Rod";
            case 53 -> "Cursed Land";
            case 54 -> "Cyclopean Tomb";
            case 55 -> "Dark Ritual";
            case 56 -> "Darkpact";
            case 57 -> "Death Ward";
            case 58 -> "Deathgrip";
            case 59 -> "Deathlace";
            case 60 -> "Demonic Attorney";
            case 61 -> "Demonic Hordes";
            case 62 -> "Demonic Tutor";
            case 63 -> "Dingus Egg";
            case 64 -> "Disenchant";
            case 65 -> "Disintegrate";
            case 66 -> "Disrupting Scepter";
            case 67 -> "Dragon Whelp";
            case 68 -> "Drain Life";
            case 69 -> "Drain Power";
            case 70 -> "Drudge Skeletons";
            case 71 -> "Dwarven Demolition Team";
            case 72 -> "Dwarven Warriors";
            case 73 -> "Earth Elemental";
            case 74 -> "Earthbind";
            case 75 -> "Earthquake";
            case 76 -> "Elvish Archers";
            case 77 -> "Evil Presence";
            case 78 -> "False Orders";
            case 79 -> "Farmstead";
            case 80 -> "Fastbond";
            case 81 -> "Fear";
            case 82 -> "Feedback";
            case 83 -> "Fire Elemental";
            case 84 -> "Fireball";
            case 85 -> "Firebreathing";
            case 86 -> "Flashfires";
            case 87 -> "Flight";
            case 88 -> "Fog";
            case 89 -> "Force of Nature";
            case 90 -> "Forcefield";
            case 91 -> "Forest";
            case 92 -> "Fork";
            case 93 -> "Frozen Shade";
            case 94 -> "Fungusaur";
            case 95 -> "Gaea's Liege";
            case 96 -> "Gauntlet of Might";
            case 97 -> "Giant Growth";
            case 98 -> "Giant Spider";
            case 99 -> "Glasses of Urza";
            case 100 -> "Gloom";
            case 101 -> "Goblin Balloon Brigade";
            case 102 -> "Goblin King";
            case 103 -> "Granite Gargoyle";
            case 104 -> "Gray Ogre";
            case 105 -> "Green Ward";
            case 106 -> "Grizzly Bears";
            case 107 -> "Guardian Angel";
            case 108 -> "Healing Salve";
            case 109 -> "Helm of Chatzuk";
            case 110 -> "Hill Giant";
            case 111 -> "Holy Armor";
            case 112 -> "Holy Strength";
            case 113 -> "Howl from Beyond";
            case 114 -> "Howling Mine";
            case 115 -> "Hurloon Minotaur";
            case 116 -> "Hurricane";
            case 117 -> "Hypnotic Specter";
            case 118 -> "Ice Storm";
            case 119 -> "Icy Manipulator";
            case 120 -> "Illusionary Mask";
            case 121 -> "Instill Energy";
            case 122 -> "Invisibility";
            case 123 -> "Iron Star";
            case 124 -> "Ironclaw Orcs";
            case 125 -> "Ironroot Treefolk";
            case 126 -> "Island";
            case 127 -> "Island Sanctuary";
            case 128 -> "Ivory Cup";
            case 129 -> "Jade Monolith";
            case 130 -> "Jade Statue";
            case 131 -> "Jayemdae Tome";
            case 132 -> "Juggernaut";
            case 133 -> "Jump";
            case 134 -> "Karma";
            case 135 -> "Keldon Warlord";
            case 136 -> "Kormus Bell";
            case 137 -> "Kudzu";
            case 138 -> "Lance";
            case 139 -> "Ley Druid";
            case 140 -> "Library of Leng";
            case 141 -> "Lich";
            case 142 -> "Lifeforce";
            case 143 -> "Lifelace";
            case 144 -> "Lifetap";
            case 145 -> "Lightning Bolt";
            case 146 -> "Living Artifact";
            case 147 -> "Living Lands";
            case 148 -> "Living Wall";
            case 149 -> "Llanowar Elves";
            case 150 -> "Lord of Atlantis";
            case 151 -> "Lord of the Pit";
            case 152 -> "Lure";
            case 153 -> "Magical Hack";
            case 154 -> "Mahamoti Djinn";
            case 155 -> "Mana Flare";
            case 156 -> "Mana Short";
            case 157 -> "Mana Vault";
            case 158 -> "Manabarbs";
            case 159 -> "Meekstone";
            case 160 -> "Merfolk of the Pearl Trident";
            case 161 -> "Mesa Pegasus";
            case 162 -> "Mind Twist";
            case 163 -> "Mons Goblin Raiders";
            case 164 -> "Mountain";
            case 165 -> "Mox Emerald";
            case 166 -> "Mox Jet";
            case 167 -> "Mox Pearl";
            case 168 -> "Mox Ruby";
            case 169 -> "Mox Sapphire";
            case 170 -> "Natural Selection";
            case 171 -> "Nether Shadow";
            case 172 -> "Nettling Imp";
            case 173 -> "Nevinyrral's Disk";
            case 174 -> "Nightmare";
            case 175 -> "Northern Paladin";
            case 176 -> "Obsianus Golem";
            case 177 -> "Orcish Artillery";
            case 178 -> "Orcish Oriflamme";
            case 179 -> "Paralyze";
            case 180 -> "Pearled Unicorn";
            case 181 -> "Personal Incarnation";
            case 182 -> "Pestilence";
            case 183 -> "Phantasmal Forces";
            case 184 -> "Phantasmal Terrain";
            case 185 -> "Phantom Monster";
            case 186 -> "Pirate Ship";
            case 187 -> "Plague Rats";
            case 188 -> "Plains";
            case 189 -> "Plateau";
            case 190 -> "Power Leak";
            case 191 -> "Power Sink";
            case 192 -> "Power Surge";
            case 193 -> "Prodigal Sorcerer";
            case 194 -> "Psionic Blast";
            case 195 -> "Psychic Venom";
            case 196 -> "Purelace";
            case 197 -> "Raging River";
            case 198 -> "Raise Dead";
            case 199 -> "Red Elemental Blast";
            case 200 -> "Red Ward";
            case 201 -> "Regeneration";
            case 202 -> "Regrowth";
            case 203 -> "Resurrection";
            case 204 -> "Reverse Damage";
            case 205 -> "Righteousness";
            case 206 -> "Roc of Kher Ridges";
            case 207 -> "Rock Hydra";
            case 208 -> "Rod of Ruin";
            case 209 -> "Royal Assassin";
            case 210 -> "Sacrifice";
            case 211 -> "Samite Healer";
            case 212 -> "Savannah";
            case 213 -> "Savannah Lions";
            case 214 -> "Scathe Zombies";
            case 215 -> "Scavenging Ghoul";
            case 216 -> "Scrubland";
            case 217 -> "Scryb Sprites";
            case 218 -> "Sea Serpent";
            case 219 -> "Sedge Troll";
            case 220 -> "Sengir Vampire";
            case 221 -> "Serra Angel";
            case 222 -> "Shanodin Dryads";
            case 223 -> "Shatter";
            case 224 -> "Shivan Dragon";
            case 225 -> "Simulacrum";
            case 226 -> "Sinkhole";
            case 227 -> "Siren's Call";
            case 228 -> "Sleight of Mind";
            case 229 -> "Smoke";
            case 230 -> "Sol Ring";
            case 231 -> "Soul Net";
            case 232 -> "Spell Blast";
            case 233 -> "Stasis";
            case 234 -> "Steal Artifact";
            case 235 -> "Stone Giant";
            case 236 -> "Stone Rain";
            case 237 -> "Stream of Life";
            case 238 -> "Sunglasses of Urza";
            case 239 -> "Swamp";
            case 240 -> "Swords to Plowshares";
            case 241 -> "Taiga";
            case 242 -> "Terror";
            case 243 -> "The Hive";
            case 244 -> "Thicket Basilisk";
            case 245 -> "Thoughtlace";
            case 246 -> "Throne of Bone";
            case 247 -> "Timber Wolves";
            case 248 -> "Time Vault";
            case 249 -> "Time Walk";
            case 250 -> "Timetwister";
            case 251 -> "Tranquility";
            case 252 -> "Tropical Island";
            case 253 -> "Tsunami";
            case 254 -> "Tundra";
            case 255 -> "Tunnel";
            case 256 -> "Twiddle";
            case 257 -> "Two Headed Giant of Foriys";
            case 258 -> "Underground Sea";
            case 259 -> "Unholy Strength";
            case 260 -> "Unsummon";
            case 261 -> "Uthden Troll";
            case 262 -> "Verduran Enchantress";
            case 263 -> "Vesuvan Doppleganger";
            case 264 -> "Veteran Bodyguard";
            case 265 -> "Volcanic Eruption";
            case 266 -> "Volcanic Island";
            case 267 -> "Wall of Air";
            case 268 -> "Wall of Bone";
            case 269 -> "Wall of Brambles";
            case 270 -> "Wall of Fire";
            case 271 -> "Wall of Ice";
            case 272 -> "Wall of Stone";
            case 273 -> "Wall of Swords";
            case 274 -> "Wall of Water";
            case 275 -> "Wall of Wood";
            case 276 -> "Wanderlust";
            case 277 -> "War Mammoth";
            case 278 -> "Warp Artifact";
            case 279 -> "Water Elemental";
            case 280 -> "Weakness";
            case 281 -> "Web";
            case 282 -> "Wheel of Fortune";
            case 283 -> "White Knight";
            case 284 -> "White Ward";
            case 285 -> "Wild Growth";
            case 286 -> "Will-O'-The-Wisp";
            case 287 -> "Winter Orb";
            case 288 -> "Wooden Sphere";
            case 289 -> "Word of Command";
            case 290 -> "Wrath of God";
            case 291 -> "Zombie Master";
            case 292 -> "Amnesia";
            case 293 -> "Angry Mob";
            case 294 -> "Ashes to Ashes";
            case 295 -> "Ball Lightning";
            case 296 -> "Banshee";
            case 297 -> "Barl's Cage";
            case 298 -> "Dark Heart of the Wood";
            case 299 -> "Blood Moon";
            case 300 -> "Apprentice Wizard";
            case 301 -> "Blood of the Martyr";
            case 302 -> "Bone Flute";
            case 303 -> "Brainwash";
            case 304 -> "Brothers of Fire";
            case 305 -> "Carnivorous Plant";
            case 306 -> "Cave People";
            case 307 -> "City of Shadows";
            case 308 -> "Coal Golem";
            case 309 -> "Dance of Many";
            case 310 -> "Deep Water";
            case 311 -> "Dust to Dust";
            case 312 -> "Eater of the Dead";
            case 313 -> "Elves of Deep Shadow";
            case 314 -> "Erosion";
            case 315 -> "Eternal Flame";
            case 316 -> "Exorcist";
            case 317 -> "Fasting";
            case 318 -> "Fellwar Stone";
            case 319 -> "Fire and Brimstone";
            case 320 -> "Fire Drake";
            case 321 -> "Fissure";
            case 322 -> "Scarwood Hag";
            case 323 -> "People of the Woods";
            case 324 -> "Fountain of Youth";
            case 325 -> "Frankenstein's Monster";
            case 326 -> "Ghost Ship";
            case 327 -> "Giant Shark";
            case 328 -> "Spitting Slug";
            case 329 -> "Goblin Caves";
            case 330 -> "Goblin Hero";
            case 331 -> "Goblin Wizard";
            case 332 -> "Goblins of the Flarg";
            case 333 -> "Grave Robbers";
            case 334 -> "Gaea's Touch";
            case 335 -> "Hidden Path";
            case 336 -> "Bog Imp";
            case 337 -> "Inferno";
            case 338 -> "Knights of Thorn";
            case 339 -> "Land Leeches";
            case 340 -> "Leviathan";
            case 341 -> "Living Armor";
            case 342 -> "Lurker";
            case 343 -> "Mana Clash";
            case 344 -> "Mana Vortex";
            case 345 -> "Martyr's Cry";
            case 346 -> "Mind Bomb";
            case 347 -> "Morale";
            case 348 -> "Necropolis";
            case 349 -> "Orc General";
            case 350 -> "Bog Rats";
            case 351 -> "Preacher";
            case 352 -> "Psychic Allergy";
            case 353 -> "Book of Rass";
            case 354 -> "Reflecting Mirror";
            case 355 -> "Riptide";
            case 356 -> "Runesword";
            case 357 -> "Safe Haven";
            case 358 -> "Scarecrow";
            case 359 -> "Season of the Witch";
            case 360 -> "Sisters of the Flame";
            case 361 -> "Skull of Orm";
            case 362 -> "Standing Stones";
            case 363 -> "Stone Calender";
            case 364 -> "Sunken City";
            case 365 -> "Marsh Gas";
            case 366 -> "Marsh Goblins";
            case 367 -> "Cleansing";
            case 368 -> "Tormod's Crypt";
            case 369 -> "Dark Sphere";
            case 370 -> "The Drowned";
            case 371 -> "Murk Dwellers";
            case 372 -> "The Fallen";
            case 373 -> "Niall Silvain";
            case 374 -> "Inquisition";
            case 375 -> "Holy Light";
            case 376 -> "Diabolic Machine";
            case 377 -> "Maze of Ith";
            case 378 -> "Nameless Race";
            case 379 -> "Tower of Coireall";
            case 380 -> "Tracker";
            case 381 -> "Sorrow's Path";
            case 382 -> "Uncle Istvan";
            case 383 -> "Venom";
            case 384 -> "Wand of Ith";
            case 385 -> "War Barge";
            case 386 -> "Whippoorwill";
            case 387 -> "Witch Hunter";
            case 388 -> "Word of Binding";
            case 389 -> "Wormwood Treefolk";
            case 390 -> "Worms of the Earth";
            case 391 -> "Abu Jafar";
            case 392 -> "Aladdin";
            case 393 -> "Aladdin's Lamp";
            case 394 -> "Ali Baba";
            case 395 -> "Ali from Cairo";
            case 396 -> "Aladdin's Ring";
            case 397 -> "Army of Allah";
            case 398 -> "Bazaar of Baghdad";
            case 399 -> "Bird Maiden";
            case 400 -> "Bottle of Suleiman";
            case 401 -> "Camel";
            case 402 -> "City in a Bottle";
            case 403 -> "City of Brass";
            case 404 -> "Cuombajj Witches";
            case 405 -> "Cyclone";
            case 406 -> "Dandan";
            case 407 -> "Desert";
            case 408 -> "Desert Nomads";
            case 409 -> "Desert Twister";
            case 410 -> "Diamond Valley";
            case 411 -> "Drop of Honey";
            case 412 -> "Ebony Horse";
            case 413 -> "El-Hajjaj";
            case 414 -> "Elephant Graveyard";
            case 415 -> "Erg Raiders";
            case 416 -> "Erhnam Djinn";
            case 417 -> "Eye for an Eye";
            case 418 -> "Fishliver Oil";
            case 419 -> "Flying Carpet";
            case 420 -> "Flying Men";
            case 421 -> "Ghazban Ogre";
            case 422 -> "Giant Tortoise";
            case 423 -> "Guardian Beast";
            case 424 -> "Hasran Ogress";
            case 425 -> "Hurr Jackal";
            case 426 -> "Ifh-Biff Efreet";
            case 427 -> "Island Fish Jasconius";
            case 428 -> "Island of Wak-Wak";
            case 429 -> "Jandor's Ring";
            case 430 -> "Jandor's Saddlebags";
            case 431 -> "Jeweled Bird";
            case 432 -> "Jihad";
            case 433 -> "Junun Efreet";
            case 434 -> "Juzam Djinn";
            case 435 -> "Khabal Ghoul";
            case 436 -> "King Suleiman";
            case 437 -> "Kird Ape";
            case 438 -> "Library of Alexandria";
            case 439 -> "Magnetic Mountain";
            case 440 -> "Merchant Ship";
            case 441 -> "Metamorphosis";
            case 442 -> "Mijae Djinn";
            case 443 -> "Moorish Cavalry";
            case 444 -> "Nafs Asp";
            case 445 -> "Oasis";
            case 446 -> "Old Man of the Sea";
            case 447 -> "Oubliette";
            case 448 -> "Piety";
            case 449 -> "Pyramids";
            case 450 -> "Repentant Blacksmith";
            case 451 -> "Ring of Maruf";
            case 452 -> "Rukh Egg";
            case 453 -> "Sandals of Abdallah";
            case 454 -> "Sandstorm";
            case 455 -> "Serendib Djinn";
            case 456 -> "Serendib Efreet";
            case 457 -> "Shahrazad";
            case 458 -> "Sindbad";
            case 459 -> "Singing Tree";
            case 460 -> "Sorceress Queen";
            case 461 -> "Stone Throwing Devils";
            case 462 -> "Unstable Mutation";
            case 463 -> "War Elephant";
            case 464 -> "Wyluli Wolf";
            case 465 -> "Ydwen Efreet";
            case 466 -> "Amulet of Kroog";
            case 467 -> "Argivian Archaeoligist";
            case 468 -> "Argivian Blacksmith";
            case 469 -> "Argothian Pixies";
            case 470 -> "Argothian Treefolk";
            case 471 -> "Armageddon Clock";
            case 472 -> "Artifact Blast";
            case 473 -> "Artifact Ward";
            case 474 -> "Ashnod's Altar";
            case 475 -> "Ashnod's Battle Gear";
            case 476 -> "Ashnod's Transmogrant";
            case 477 -> "Atog";
            case 478 -> "Battering Ram";
            case 479 -> "Bronze Tablet";
            case 480 -> "Candelabra of Tawnos";
            case 481 -> "Circle of Protection: Artifacts";
            case 482 -> "Citanul Druid";
            case 483 -> "Clay Statue";
            case 484 -> "Clockwork Avian";
            case 485 -> "Colossus of Sardia";
            case 486 -> "Coral Helm";
            case 487 -> "Crumble";
            case 488 -> "Cursed Rack";
            case 489 -> "Damping Field";
            case 490 -> "Detonate";
            case 491 -> "Drafna's Restoration";
            case 492 -> "Dragon Engine";
            case 493 -> "Dwarven Weaponsmith";
            case 494 -> "Energy Flux";
            case 495 -> "Feldon's Cane";
            case 496 -> "Gaea's Avenger";
            case 497 -> "Gate to Phyrexia";
            case 498 -> "Goblin Artisans";
            case 499 -> "Golgothian Sylex";
            case 500 -> "Grapeshot Catapult";
            case 501 -> "Haunting Wind";
            case 502 -> "Hurkyl's Recall";
            case 503 -> "Ivory Tower";
            case 504 -> "Jalum Tome";
            case 505 -> "Martyrs of Korlis";
            case 506 -> "Mightstone";
            case 507 -> "Millstone";
            case 508 -> "Mishra's Factory";
            case 509 -> "Mishra's War Machine";
            case 510 -> "Mishra's Workshop";
            case 511 -> "Obelisk of Undoing";
            case 512 -> "Onulet";
            case 513 -> "Orcish Mechanics";
            case 514 -> "Ornithopter";
            case 515 -> "Phyrexian Gremlins";
            case 516 -> "Artifact Possession";
            case 517 -> "Power Artifact";
            case 518 -> "Powerleech";
            case 519 -> "Primal Clay";
            case 520 -> "Rakalite";
            case 521 -> "Reconstruction";
            case 522 -> "Reverse Polarity";
            case 523 -> "Rocket Launcher";
            case 524 -> "Sage of Lat-Nam";
            case 525 -> "Shapeshifter";
            case 526 -> "Shatterstorm";
            case 527 -> "Staff of Zegon";
            case 528 -> "Strip Mine";
            case 529 -> "Su-Chi";
            case 530 -> "Tablet of Epityr";
            case 531 -> "Tawnos's Coffin";
            case 532 -> "Tawnos's Wand";
            case 533 -> "Tawnos's Weaponry";
            case 534 -> "Tetravus";
            case 535 -> "The Rack";
            case 536 -> "Titania's Song";
            case 537 -> "Transmute Artifact";
            case 538 -> "Triskelion";
            case 539 -> "Urza's Avenger";
            case 540 -> "Urza's Chalice";
            case 541 -> "Urza's Mine";
            case 542 -> "Urza's Miter";
            case 543 -> "Urza's Power Plant";
            case 544 -> "Urza's Tower";
            case 545 -> "Wall of Spears";
            case 546 -> "Weakstone";
            case 547 -> "Xenic Poltergeist";
            case 548 -> "Yawgmoth Demon";
            case 549 -> "Priest of Yawgmoth";
            case 550 -> "Yotian Soldiers";
            case 551 -> "Abomination";
            case 552 -> "Acid Rain";
            case 553 -> "Active Volcano";
            case 554 -> "Adun Oakenshield";
            case 555 -> "Adventurers' Guildhouse";
            case 556 -> "Aerathi Berserker";
            case 557 -> "Aisling Leprechaun";
            case 558 -> "Akron Legionnaire";
            case 559 -> "Al-abara's Carpet";
            case 560 -> "Alabaster Potion";
            case 561 -> "Alchor's Tomb";
            case 562 -> "All Hallows Eve";
            case 563 -> "Amrou Kithkin";
            case 564 -> "Angelic Voices";
            case 565 -> "Angus Mackenzie";
            case 566 -> "Anti-Magic Aura";
            case 567 -> "Arboria";
            case 568 -> "Arcades Sabboth";
            case 569 -> "Arena of the Ancients";
            case 570 -> "Avoid Fate";
            case 571 -> "Axelrod Gunnarson";
            case 572 -> "Ayesha Tanaka";
            case 573 -> "Azure Drake";
            case 574 -> "Backdraft";
            case 575 -> "Backfire";
            case 576 -> "Barbary Apes";
            case 577 -> "Barktooth Warbeard";
            case 578 -> "Bartel Runeaxe";
            case 579 -> "Beasts of Bogardan";
            case 580 -> "Black Mana Battery";
            case 581 -> "Blazing Effigy";
            case 582 -> "Blight";
            case 583 -> "Blood Lust";
            case 584 -> "Blue Mana Battery";
            case 585 -> "Boomerang";
            case 586 -> "Boris Devilboon";
            case 587 -> "Brine Hag";
            case 588 -> "Bronze Horse";
            case 589 -> "Carrion Ants";
            case 590 -> "Cat Warriors";
            case 591 -> "Cathedral of Serra";
            case 592 -> "Caverns of Despair";
            case 593 -> "Chain Lightning";
            case 594 -> "Chains of Mephistopholes";
            case 595 -> "Chromium";
            case 596 -> "Cleanse";
            case 597 -> "Clergy of the Holy Nimbus";
            case 598 -> "Cocoon";
            case 599 -> "Concordant Crossroads";
            case 600 -> "Cosmic Horror";
            case 601 -> "Craw Giant";
            case 602 -> "Crevasse";
            case 603 -> "Crimson Kobolds";
            case 604 -> "Crimson Manticore";
            case 605 -> "Crookshank Kobolds";
            case 606 -> "Cyclopean Mummy";
            case 607 -> "D'Avenant Archer";
            case 608 -> "Dakkon Blackblade";
            case 609 -> "Darkness";
            case 610 -> "Deadfall";
            case 611 -> "Demonic Torment";
            case 612 -> "Devouring Deep";
            case 613 -> "Disharmony";
            case 614 -> "Divine Intervention";
            case 615 -> "Divine Offering";
            case 616 -> "Divine Transformation";
            case 617 -> "Dream Coat";
            case 618 -> "Durkwood Boars";
            case 619 -> "Dwarven Song";
            case 620 -> "Elder Land Wurm";
            case 621 -> "Elder Spawn";
            case 622 -> "Elven Riders";
            case 623 -> "Emerald Dragonfly";
            case 624 -> "Enchanted Being";
            case 625 -> "Enchantment Alteration";
            case 626 -> "Energy Tap";
            case 627 -> "Equinox";
            case 628 -> "Eternal Warrior";
            case 629 -> "Eureka";
            case 630 -> "Evil Eye of Orms-by-Gore";
            case 631 -> "Fallen Angel";
            case 632 -> "Falling Star";
            case 633 -> "Feint";
            case 634 -> "Field of Dreams";
            case 635 -> "Fire Sprites";
            case 636 -> "Firestorm Phoenix";
            case 637 -> "Flash Counter";
            case 638 -> "Flash Flood";
            case 639 -> "Floral Spuzzem";
            case 640 -> "Force Spike";
            case 641 -> "Forethought Amulet";
            case 642 -> "Fortified Area";
            case 643 -> "Frost Giant";
            case 644 -> "Gabriel Angelfire";
            case 645 -> "Gaseous Form";
            case 646 -> "Gauntlets of Chaos";
            case 647 -> "Ghosts of the Damned";
            case 648 -> "Giant Slug";
            case 649 -> "Giant Strength";
            case 650 -> "Giant Turtle";
            case 651 -> "Glyph of Delusion";
            case 652 -> "Glyph of Destruction";
            case 653 -> "Glyph of Doom";
            case 654 -> "Glyph of Life";
            case 655 -> "Glyph of Reincarnation";
            case 656 -> "Gosta Dirk";
            case 657 -> "Gravity Sphere";
            case 658 -> "Great Defender";
            case 659 -> "Great Wall";
            case 660 -> "Greater Realm of Preservation";
            case 661 -> "Greed";
            case 662 -> "Green Mana Battery";
            case 663 -> "Gwendlyn Di Corci";
            case 664 -> "Halfdane";
            case 665 -> "Hammerheim";
            case 666 -> "Hazezon Tamar";
            case 667 -> "Headless Horseman";
            case 668 -> "Heaven's Gate";
            case 669 -> "Hell Swarm";
            case 670 -> "Hell's Caretaker";
            case 671 -> "Hellfire";
            case 672 -> "Holy Day";
            case 673 -> "Horn of Deafening";
            case 674 -> "Hornet Cobra";
            case 675 -> "Horror of Horrors";
            case 676 -> "Hunding Gjornersen";
            case 677 -> "Hyperion Blacksmith";
            case 678 -> "Ichneumon Druid";
            case 679 -> "Immolation";
            case 680 -> "Imprison";
            case 681 -> "In the Eye of Chaos";
            case 682 -> "Indestructable Aura";
            case 683 -> "Infernal Medusa";
            case 684 -> "Infinite Authority";
            case 685 -> "Invoke Prejudice";
            case 686 -> "Ivory Guardians";
            case 687 -> "Jacques le Vert";
            case 688 -> "Jasmine Boreal";
            case 689 -> "Jedit Ojanen";
            case 690 -> "Jerrard of the Closed Fist";
            case 691 -> "Johan";
            case 692 -> "Jovial Evil";
            case 693 -> "Juxtapose";
            case 694 -> "Karakas";
            case 695 -> "Kasimer the Lone Wolf";
            case 696 -> "Keepers of the Faith";
            case 697 -> "Kei Takahashi";
            case 698 -> "Killer Bees";
            case 699 -> "Kismet";
            case 700 -> "Knowledge Vault";
            case 701 -> "Kobold Drill Sergeant";
            case 702 -> "Kobold Overlord";
            case 703 -> "Kobold Taskmaster";
            case 704 -> "Kobolds of Kher Keep";
            case 705 -> "Kry Shield";
            case 706 -> "Lady Caleria";
            case 707 -> "Lady Evangela";
            case 708 -> "Lady Orca";
            case 709 -> "Land Equilibrium";
            case 710 -> "Land Tax";
            case 711 -> "Land's Edge";
            case 712 -> "Lesser Werewolf";
            case 713 -> "Life Chisel";
            case 714 -> "Life Matrix";
            case 715 -> "Lifeblood";
            case 716 -> "Living Plane";
            case 717 -> "Livonya Silone";
            case 718 -> "Lord Magnus";
            case 719 -> "Lost Soul";
            case 720 -> "Mana Drain";
            case 721 -> "Mana Matrix";
            case 722 -> "Marble Priest";
            case 723 -> "Marhault Elsdragon";
            case 724 -> "Master of the Hunt";
            case 725 -> "Mirror Universe";
            case 726 -> "Moat";
            case 727 -> "Mold Demon";
            case 728 -> "Moss Monster";
            case 729 -> "Mountain Stronghold";
            case 730 -> "Mountain Yeti";
            case 731 -> "Nebuchadnezzar";
            case 732 -> "Nether Void";
            case 733 -> "Nicol Bolas";
            case 734 -> "North Star";
            case 735 -> "Nova Pentacle";
            case 736 -> "Osai Vultures";
            case 737 -> "Palladia-Mors";
            case 738 -> "Part Water";
            case 739 -> "Pavel Maliki";
            case 740 -> "Pendelhaven";
            case 741 -> "Petra Sphinx";
            case 742 -> "Pit Scorpion";
            case 743 -> "Pixie Queen";
            case 744 -> "Planar Gate";
            case 745 -> "Pradesh Gypsies";
            case 746 -> "Presence of the Master";
            case 747 -> "Primordial Ooze";
            case 748 -> "Princess Lucrezia";
            case 749 -> "Psionic Entity";
            case 750 -> "Psychic Purge";
            case 751 -> "Puppet Master";
            case 752 -> "Pyrotechnics";
            case 753 -> "Quagmire";
            case 754 -> "Quarum Trench Gnomes";
            case 755 -> "Rabid Wombat";
            case 756 -> "Radjan Spirit";
            case 757 -> "Raging Bull";
            case 758 -> "Ragnar";
            case 759 -> "Ramirez DePietro";
            case 760 -> "Ramses Overdark";
            case 761 -> "Rapid Fire";
            case 762 -> "Rasputin Dreamweaver";
            case 763 -> "Rebirth";
            case 764 -> "Recall";
            case 765 -> "Red Mana Battery";
            case 766 -> "Reincarnation";
            case 767 -> "Relic Barrier";
            case 768 -> "Relic Bind";
            case 769 -> "Remove Enchantment";
            case 770 -> "Remove Soul";
            case 771 -> "Reset";
            case 772 -> "Revelation";
            case 773 -> "Reverberation";
            case 774 -> "Righteous Avengers";
            case 775 -> "Ring of Immortals";
            case 776 -> "Riven Turnbull";
            case 777 -> "Rohgahh of Kher Keep";
            case 778 -> "Rust";
            case 779 -> "Sea Kings' Blessing";
            case 780 -> "Seafarer's Quay";
            case 781 -> "Seeker";
            case 782 -> "Segovian Leviathan";
            case 783 -> "Sentinel";
            case 784 -> "Serpent Generator";
            case 785 -> "Shelkin Brownie";
            case 786 -> "Shield Wall";
            case 787 -> "Shimian Night Stalker";
            case 788 -> "Silhouette";
            case 789 -> "Sir Shandlar of Eberyn";
            case 790 -> "Sivitri Scarzam";
            case 791 -> "Sol'kanar the Swamp King";
            case 792 -> "Spectral Cloak";
            case 793 -> "Spinal Villain";
            case 794 -> "Spirit Link";
            case 795 -> "Spirit Shackle";
            case 796 -> "Spiritual Sanctuary";
            case 797 -> "Stangg";
            case 798 -> "Storm Seeker";
            case 799 -> "Storm World";
            case 800 -> "Subdue";
            case 801 -> "Sunastian Falconer";
            case 802 -> "Sword of the Ages";
            case 803 -> "Sylvan Library";
            case 804 -> "Sylvan Paradise";
            case 805 -> "Syphon Soul";
            case 806 -> "Tabernacle at Pendrell Vale";
            case 807 -> "Takklemaggot";
            case 808 -> "Telekinesis";
            case 809 -> "Teleport";
            case 810 -> "Tempest Efreet";
            case 811 -> "Tetsuo Umezawa";
            case 812 -> "The Abyss";
            case 813 -> "The Brute";
            case 814 -> "The Lady of the Mountain";
            case 815 -> "The Wretched";
            case 816 -> "Thunder Spirit";
            case 817 -> "Time Elemental";
            case 818 -> "Tobias Andrion";
            case 819 -> "Tolaria";
            case 820 -> "Tor Wauki";
            case 821 -> "Torsten Von Ursus";
            case 822 -> "Touch of Darkness";
            case 823 -> "Transmutation";
            case 824 -> "Triassic Egg";
            case 825 -> "Tuknir Deathlock";
            case 826 -> "Tundra Wolves";
            case 827 -> "Typhoon";
            case 828 -> "Undertow";
            case 829 -> "Underworld Dreams";
            case 830 -> "Unholy Citadel";
            case 831 -> "Untamed Wilds";
            case 832 -> "Ur-Drago";
            case 833 -> "Urborg";
            case 834 -> "Vaevictis Asmadi";
            case 835 -> "Vampire Bats";
            case 836 -> "Venarian Gold";
            case 837 -> "Visions";
            case 838 -> "Voodoo Doll";
            case 839 -> "Walking Dead";
            case 840 -> "Wall of Caltrops";
            case 841 -> "Wall of Dust";
            case 842 -> "Wall of Earth";
            case 843 -> "Wall of Heat";
            case 844 -> "Wall of Light";
            case 845 -> "Wall of Opposition";
            case 846 -> "Wall of Putrid Flesh";
            case 847 -> "Wall of Shadows";
            case 848 -> "Wall of Tombstones";
            case 849 -> "Wall of Vapor";
            case 850 -> "Wall of Wonder";
            case 851 -> "Whirling Dervish";
            case 852 -> "White Mana Battery";
            case 853 -> "Willow Satyr";
            case 854 -> "Winds of Change";
            case 855 -> "Winter Blast";
            case 856 -> "Wolverine Pack";
            case 857 -> "Wood Elemental";
            case 858 -> "Xira Arien";
            case 859 -> "Zephyr Falcon";
            case 860 -> "Call from the Grave";
            case 861 -> "Prismatic Dragon";
            case 862 -> "Knights of the Rainbow Vale";
            case 863 -> "Pandora's Box";
            case 864 -> "Whimsy";
            case 865 -> "Faerie Dragon";
            case 866 -> "Goblin Polka Band";
            case 867 -> "Power Struggle";
            case 868 -> "Aswan Jaguar";
            case 869 -> "Orcish Catapult";
            case 870 -> "Gem Bazaar";
            case 871 -> "Necropolis of Azaar";
            case 872 -> "Red Guild";
            case 873 -> "Blue Guild";
            case 874 -> "White Guild";
            case 875 -> "Green Guild";
            case 876 -> "Black Guild";
            case 877 -> "Artificer's Guild";
            case 878 -> "Bright Society";
            case 879 -> "Grey Society";
            case 880 -> "Dark Society";
            case 881 -> "Gladiator";
            case 882 -> "Master";
            case 883 -> "Royalty";
            case 884 -> "Veteran";
            case 885 -> "Giant Wasp";
            case 886 -> "Wolves of the Hunt";
            case 887 -> "Poison Snake";
            case 888 -> "Minor Demon";
            case 889 -> "Sand Warrior";
            case 890 -> "Djinn of the Bottle";
            case 891 -> "Tetravite";
            case 892 -> "Rukh";
            case 893 -> "Stangg Twin";
            case 894 -> "Mana Crypt";
            case 895 -> "Nalathni Dragon";
            case 896 -> "Sewers of Estark";
            case 897 -> "Windseeker Centaur";
            case 898 -> "Giant Badger";
            case 899 -> "Arena";
            case 900 -> "Spawn of Azar";
            case 901 -> "Damage";
            case 902 -> "Legacy";
            case 903 -> "Effect";
            case 904 -> "Draw Card";
            case 905 -> "Hunting";
            case 906 -> "Blank";
            case 907 -> "Blank";
            case 908 -> "Blank";
            case 909 -> "Blank";
            case 910 -> "Assembly Worker";
            case 911 -> "Blank";
            case 912 -> "Blank";
            case 913 -> "Blank";
            case 914 -> "Blank";
            case 915 -> "Blank";
            case 916 -> "Blank";
            case 917 -> "Blank";
            case 918 -> "Blank";
            case 919 -> "Blank";
            case 920 -> "Blank";
            case 921 -> "Blank";
            case 922 -> "Blank";
            case 923 -> "Blank";
            case 924 -> "Blank";
            case 925 -> "Blank";
            case 926 -> "Blank";
            case 927 -> "Blank";
            case 928 -> "Blank";
            case 929 -> "Blank";
            case 930 -> "Brass Man";
            case 931 -> "Dancing Scimitar";
            case 932 -> "Curse Artifact";
            case 933 -> "Electric Eel";
            case 934 -> "Festival";
            case 935 -> "Flood";
            case 936 -> "Goblin Digging Team";
            case 937 -> "Goblin Rock Sled";
            case 938 -> "Goblin Shrine";
            case 939 -> "Marsh Viper";
            case 940 -> "Merfolk Assassin";
            case 941 -> "Miracle Worker";
            case 942 -> "Pikemen";
            case 943 -> "Ragman";
            case 944 -> "Savaen Elves";
            case 945 -> "Scarwood Bandits";
            case 946 -> "Scarwood Goblins";
            case 947 -> "Scavenger Folk";
            case 948 -> "Squire";
            case 949 -> "Tangle Kelp";
            case 950 -> "Tivadar's Crusade";
            case 951 -> "Water Wurm";
            case 952 -> "Rubinia Soulsinger";
            case 953 -> "MPS Logo";
            case 954 -> "Blank";
            case 955 -> "Blank";
            case 956 -> "Blank";
            case 957 -> "Blank";
            case 958 -> "Blank";
            case 959 -> "Blank";
            case 960 -> "Blank";
            case 961 -> "Blank";
            case 962 -> "Blank";
            case 963 -> "Blank";
            case 964 -> "Blank";
            case 965 -> "Blank";
            case 966 -> "Blank";
            case 967 -> "Blank";
            case 968 -> "Blank";
            case 969 -> "Blank";
            case 970 -> "Blank";
            case 971 -> "Blank";
            case 972 -> "Blank";
            case 973 -> "Blank";
            case 974 -> "Blank";
            case 975 -> "Blank";
            case 976 -> "Blank";
            case 977 -> "Blank";
            case 978 -> "Blank";
            case 979 -> "Blank";
            case 980 -> "Crystal Ball";
            case 981 -> "Wizard of the Cost Logo";
            case 982 -> "Blank";
            case 983 -> "Blank";
            case 984 -> "Blank";
            case 985 -> "Blank";
            case 986 -> "Blank";
            case 987 -> "Blank";
            case 988 -> "Blank";
            case 989 -> "Blank";
            case 990 -> "Blank";
            case 991 -> "Blank";
            case 992 -> "Blank";
            case 993 -> "Blank";
            case 994 -> "Blank";
            case 995 -> "Blank";
            case 996 -> "Blank";
            case 997 -> "Blank";
            case 998 -> "Blank";
            case 999 -> "Blank";
            default -> "Unknown";
        };
      
    }
      
    public int nameToDuel(String inCard){
        return 007;
    }
    
    public String gameToName(String inCard){
        if (inCard.length() == 8) inCard = inCard.substring(0, 4);
        int inCardInt = Integer.parseInt(inCard, 16);
        return switch (inCardInt) {
            case 0 -> "Swamp";
            case 1 -> "Erhnam Djinn";
            case 256 -> "Island";
            case 512 -> "Forest";
            case 768 -> "Mountain";
            case 1024 -> "Plains";
            case 1280 -> "Badlands";
            default -> "Not yet known";
        };
    }
    
    public String nameToGame(String inCard){
        return "oot";
    }    
    
    public gameDeck getGameDeck() {
    //returns a deck from a Shandalar save
        try{
            gameDeck deck = new gameDeck();
            byte[] cardArray = new byte[4];
            byte cByte;
            int i = 0;
            String j, card = "";
            gameFile.seek(deckStart); 
            cByte = gameFile.readByte();
            j = Hex(cByte);
            while (!j.equals("FF")) {
                card = card.concat(j);
                cardArray[i] = cByte;
                cByte = gameFile.readByte();
                j = Hex(cByte);
                ++i;
                if (i==4){
                    deck.add(new gameCard(card, cardMap.gameToName(card)));
                    i=0;
                    card = "";
                }
            }
            deck.group();
            return deck;
        }catch(Exception e){
            System.out.println(e.getMessage());
            return null;
        }
 }
    
    public duelDeck getDuelDeck() {
    //returns the deck from a duel format deck
        try {
            duelDeck deck = new duelDeck();
            byte[] cardArray;
            byte cByte;
            int x = 0;
            int i;
            String j, id, name, temp, amount;
            while(x!=8){
            cByte = duelFile.readByte();
            j = Hex(cByte);
            if(j.equals("3B"))
                ++x;
            }
            duelFile.skipBytes(5);
            while(duelFile.getFilePointer() < duelFile.length()-2){ //until were at the end of the duelFile
            cardArray = new byte[10];
            i = 0;
            j = "";
            temp="";
            cByte = duelFile.readByte();
            //read id of card
            while (!j.equals("09")) {
                cardArray[i] = cByte;
                ++i;
                cByte = duelFile.readByte();
                j = Hex(cByte);
            }
            cardArray[i] = -1;
            j = "";
            i = 0;
            while(cardArray[i] != -1){
            id = String.valueOf(Integer.valueOf(Hex(cardArray[i]))-30);
            temp = temp.concat(id);
            ++i;
            }//
            id = temp;
            temp="";
            cardArray = new byte[10];
            i=0;
            //read amount of card
            cByte = duelFile.readByte();
            while (!j.equals("09")) {
                cardArray[i] = cByte;
                ++i;
                cByte = duelFile.readByte();
                j = Hex(cByte);
            }
            cardArray[i]=-1;
            j="";
            i=0;
            while(cardArray[i] != -1){
            amount = String.valueOf(Integer.valueOf(Hex(cardArray[i]))-30);
            temp = temp.concat(amount);
            ++i;
            }//
            amount = temp;
            temp="";
            cardArray = new byte[50];
            i=0;
            //read the card name
            cByte = duelFile.readByte();
            while (!j.equals("0D")) {
                cardArray[i]=cByte;
                ++i;
                cByte = duelFile.readByte();
                j = Hex(cByte);
            }
            name = new String(cardArray, "ascii");
            name =  name.trim();
            //
            deck.add(new duelCard(Integer.parseInt(id), Integer.parseInt(amount), name));
            duelFile.skipBytes(2);
            }//repeat
            return deck;
        } catch (Exception e) {
                 if (e.getClass() == java.lang.ArrayIndexOutOfBoundsException.class){
            JOptionPane.showMessageDialog(this, "Array out of bounds error." + nl +
                    "This is most commonly caused by comments in the deck file, remove them " +
                    "and it should work.");
            return null;
            }
            JOptionPane.showMessageDialog(this, e);
        }
        return null;
    }    
    
    public gameDeck duelToGame(duelDeck in){
        return in.convert(cardMap);
    }
    
    public void injectToGame(gameDeck in) {
        try {
            gameFile.seek(deckStart);
            for (gameCard c : in) {
                for(int i =1; i <= c.getQuantity();++i){
                String newCardString = c.getID();
                String newCardPart = newCardString.substring(0, 2);
                byte newCardByte = (byte) Integer.parseInt(newCardPart, 16);
                gameFile.write(newCardByte);
                newCardPart = newCardString.substring(2, 4);
                newCardByte = (byte) Integer.parseInt(newCardPart, 16);
                gameFile.write(newCardByte);
                gameFile.write(1);
                gameFile.write(0);
            }
            }
            gameFile = null;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }
    
    /**
     * Clears all the cards in a game deck
     */
    public void clearDeck(){
        try {
            gameFile.seek(deckStart);
            for (int i = 0; i < 500; ++i) {
                gameFile.writeByte(255);
                gameFile.writeByte(255);
                gameFile.writeByte(255);
                gameFile.writeByte(255);
            }
            gameFile.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
    * @param args the command line arguments
    */

// To make this file open when the jar is run uncomment the below code
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInject;
    private javax.swing.JButton btnLoop;
    private javax.swing.JButton btnReadAllFiles;
    private javax.swing.JButton btnReadDuel;
    private javax.swing.JButton btnReadGame;
    private javax.swing.JButton btnWriteToFiles;
    private javax.swing.JTextArea duelDeckBox;
    private javax.swing.JTextArea gameDeckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDuelName;
    private javax.swing.JLabel lblGameName;
    private javax.swing.JMenuItem menuOpenDuel;
    private javax.swing.JMenuItem menuOpenGame;
    private javax.swing.JMenu menuTitleFile1;
    private javax.swing.JLabel statusBar;
    private javax.swing.JTextField txtBaseCard;
    private javax.swing.JTextField txtIterations;
    // End of variables declaration//GEN-END:variables
}