#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

pass() {
  printf 'ok: %s\n' "$*"
}

expect_file() {
  local path="$1"
  [ -e "$path" ] || fail "missing $path"
}

expect_tracked_file() {
  local path="$1"
  expect_file "$path"
  git ls-files --error-unmatch "$path" >/dev/null || fail "$path is not tracked"
}

expect_hash() {
  local path="$1"
  local expected="$2"
  expect_file "$path"
  local actual
  actual="$(shasum -a 256 "$path" | awk '{print $1}')"
  [ "$actual" = "$expected" ] || fail "$path sha256 $actual != $expected"
}

expect_hex_prefix() {
  local path="$1"
  local offset="$2"
  local length="$3"
  local expected="$4"
  expect_file "$path"
  local actual
  actual="$(xxd -p -l "$length" -s "$offset" "$path" | tr -d '\n')"
  [ "$actual" = "$expected" ] || fail "$path hex at $offset $actual != $expected"
}

hex_le_to_uint() {
  local hex="$1"
  local swapped=""
  local i
  for ((i=${#hex}; i>0; i-=2)); do
    swapped+="${hex:i-2:2}"
  done
  printf '%d' "0x$swapped"
}

expect_pe_dll_characteristics() {
  local path="$1"
  local expected="$2"
  expect_file "$path"
  local e_lfanew_hex e_lfanew characteristics_offset actual_le actual
  e_lfanew_hex="$(xxd -p -l 4 -s 0x3c "$path" | tr -d '\n')"
  e_lfanew="$(hex_le_to_uint "$e_lfanew_hex")"
  characteristics_offset=$((e_lfanew + 4 + 20 + 0x46))
  actual_le="$(xxd -p -l 2 -s "$characteristics_offset" "$path" | tr -d '\n')"
  actual="$(printf '%04x' "$(hex_le_to_uint "$actual_le")")"
  [ "$actual" = "$expected" ] || fail "$path PE DllCharacteristics 0x$actual != 0x$expected"
}

expect_text_match() {
  local path="$1"
  local pattern="$2"
  expect_file "$path"
  grep -Eq "$pattern" "$path" || fail "$path does not match $pattern"
}

if [ "${ALLOW_DIRTY:-0}" != "1" ]; then
  status="$(git status --short --untracked-files=all)"
  [ -z "$status" ] || fail "working tree is not clean; set ALLOW_DIRTY=1 for an in-progress local check"
  pass "working tree is clean"
else
  pass "working tree cleanliness skipped because ALLOW_DIRTY=1"
fi

if [ "${ALLOW_IGNORED_LOCAL:-0}" != "1" ]; then
  ignored_untracked="$(git status --ignored --short --untracked-files=all | awk '/^!! / {print substr($0, 4)}' | awk '$0 !~ /^\.codex\// && $0 != "security-scan-results.tsv"')"
  if [ -n "$ignored_untracked" ]; then
    printf 'FAIL: ignored local files are present; remove them or set ALLOW_IGNORED_LOCAL=1:\n' >&2
    printf '%s\n' "$ignored_untracked" >&2
    exit 1
  fi
  pass "ignored local clutter is absent, excluding autogenerated .codex files and local scan evidence"
else
  pass "ignored local clutter check skipped because ALLOW_IGNORED_LOCAL=1"
fi

tracked_ignored="$(git ls-files -ci --exclude-standard)"
[ -z "$tracked_ignored" ] || fail "unexpected tracked ignored files: ${tracked_ignored:-<none>}"
pass "tracked ignored file inventory is expected"

for path in \
  scan-targets.tsv \
  security-scan-results.tsv \
  clamscan-report.txt \
  windows-defender-report.txt \
  .codex/environments/environment.toml \
  codex-shandalar-crossover-updates-test.bundle \
  codex-shandalar-crossover-updates-test.bundle.sha256 \
  codex-shandalar-crossover-updates-test.patch \
  codex-shandalar-crossover-updates-test.patch.sha256
do
  git check-ignore -q "$path" || fail "$path is not ignored"
done
pass "local generated report/handoff files are ignored"

for path in \
  Shandalar.exe \
  zlib.dll \
  Program/zlib.dll \
  libgcc_s_dw2-1.dll \
  Program/libgcc_s_dw2-1.dll \
  Program/DuelArt/Modern.dat \
  Program/DuelArt/Planeswalker.dat \
  Program/TT0530m_.ttf \
  Program/TT0127m_.ttf \
  Program/TT0085m_.ttf \
  Program/TT0298m_.ttf \
  Program/TT0299m_.ttf \
  Program/TT0300m_.ttf \
  Program/CardArt/ManaSymbols.pic \
  Program/CardArt/Expansion_Symbols.pic \
  Program/CardArt/Watermarks.pic \
  Program/CardArt/CardCounters.png \
  Program/CardArt/Modern/Triggering.png \
  Program/CardArt/Modern/CardOv_Nyx.png \
  Program/CardArt/Planeswalker/LoyaltyBase.png \
  Program/CardArt/Planeswalker/LoyaltyMinus.png \
  Program/CardArt/Planeswalker/LoyaltyPlus.png \
  Program/CardArt/Planeswalker/LoyaltyZero.png \
  Program/Magic.exe \
  Shandalar.dll \
  Program/Shandalar.dll \
  CardArtLib.dll \
  Program/CardArtLib.dll \
  DeckDLL.dll \
  Program/Deckdll.dll \
  Drawcardlib.dll \
  Program/Drawcardlib.dll \
  ManalinkEh.dll \
  Program/ManalinkEh.dll \
  Cards.dat \
  Program/Cards.dat \
  DBInfo.dat \
  Program/DBInfo.dat \
  Rarity.dat \
  Program/Rarity.dat \
  Statwin/statscrn.tmp \
  MAGIC5.SVE \
  MAGIC5.map \
  MAGIC5.fce \
  archive/generated-local/Duel.GID \
  Duel.hlp
do
  git check-attr binary -- "$path" | grep -q ': binary: set' || fail "$path is not marked binary"
done
pass "representative binary attributes are set"

for path in \
  MENUBAK.PIC \
  Program/MENUBAK.PIC \
  WINBAK01.PIC \
  WINBAK02.PIC \
  WORLBAK1.PIC \
  Program/WINBAK01.PIC \
  Program/WINBAK02.PIC \
  Program/WORLBAK1.PIC \
  FaceMaker-Original.exe \
  FaceMaker-nores.exe \
  Program/FaceMaker-nores.exe
do
  expect_tracked_file "$path"
  git check-attr binary -- "$path" | grep -q ': binary: set' || fail "$path is not marked binary"
done
pass "protected cleanup false positives are present"

for path in \
  Program/zlib.dll \
  Program/libgcc_s_dw2-1.dll \
  Program/Manalink.ini \
  Program/DuelArt/Modern.dat \
  Program/DuelArt/Planeswalker.dat \
  Program/TT0530m_.ttf \
  Program/TT0127m_.ttf \
  Program/TT0085m_.ttf \
  Program/TT0298m_.ttf \
  Program/TT0299m_.ttf \
  Program/TT0300m_.ttf \
  Program/CardArt/ManaSymbols.pic \
  Program/CardArt/Expansion_Symbols.pic \
  Program/CardArt/Watermarks.pic \
  Program/CardArt/CardCounters.png \
  Program/CardArt/Modern/Triggering.png \
  Program/CardArt/Modern/CardOv_Nyx.png \
  Program/CardArt/Planeswalker/LoyaltyBase.png \
  Program/CardArt/Planeswalker/LoyaltyMinus.png \
  Program/CardArt/Planeswalker/LoyaltyPlus.png \
  Program/CardArt/Planeswalker/LoyaltyZero.png \
  Statwin.dll \
  Program/Statwin.dll \
  docs/bugs/ai-raw-mana-snapshot.md \
  docs/bugs/ai-etb-player-target-spell-chain-freeze.md \
  docs/bugs/piranha-marsh-spell-chain-freeze.md \
  docs/bugs/opponent-turn-ai-decision-time.md \
  docs/bugs/duel-start-coinflip-animation.md \
  src/card_id.h \
  tools/check-build-prereqs.sh \
  tools/check-source-snapshot-parity.sh \
  tools/patch-ai-decision-clamp.py \
  tools/patch-ai-decision-fallback.py \
  tools/patch-ai-raw-mana-snapshot.py \
  tools/patch-ai-player-target-selection.py \
  tools/patch-ai-etb-player-target-preselect.py \
  tools/patch-ai-land-cip-trigger-stack-bypass.py \
  tools/patch-statwin-disable-magvid-loader.py \
  tools/patch-shandalar-disable-magsnd-init.py \
  tools/patch-shandalar-magsnd-update-callback.py \
  tools/patch-shandalar-minimal-winmm-timer-callback.py \
  tools/patch-shandalar-winmm-tick-callback.py \
  tools/patch-bojuka-bog-trigger-target.py \
  tools/patch-piranha-marsh-trigger-target.py \
  tools/patch-magic-coinflip-default.py \
  tools/patch-manalink-generic-damage-prevention-guard.py \
  tools/verify-install-tree.sh
do
  expect_tracked_file "$path"
done
pass "fresh-install required files are tracked"

expect_file tools/verify-install-tree.sh
[ -x tools/verify-install-tree.sh ] || fail "tools/verify-install-tree.sh is not executable"
install_tree_output="$(tools/verify-install-tree.sh .)"
printf '%s\n' "$install_tree_output" | grep -q "Install-tree verification passed." || fail "install-tree verifier did not report success"
pass "repo root passes install-tree verification"

expect_hash Shandalar.exe 17f7af843fd2fd5424e7d36d547f4315d20fdfa840fb5050a96ab9a727a181f6
expect_hash Program/Shandalar.exe 17f7af843fd2fd5424e7d36d547f4315d20fdfa840fb5050a96ab9a727a181f6
expect_hash FaceMaker.exe 41f062874f94d732cc4feb40b568728b8462879fd3ec2bc55810f118e9c5f246
expect_hash Program/FaceMaker.exe 41f062874f94d732cc4feb40b568728b8462879fd3ec2bc55810f118e9c5f246
expect_hash FaceMaker-Original.exe 0471afcd0288a07422355ff2af224c40f8b29dc0a864eed90b3399e285f42c7e
expect_hash FaceMaker-nores.exe 43331d22d05787979af0d29cea1775fd3bcebf8acdb3c3be34524e9ca7762f4b
expect_hash Program/FaceMaker-nores.exe 43331d22d05787979af0d29cea1775fd3bcebf8acdb3c3be34524e9ca7762f4b
expect_hash Magic.exe 93a40ce2c96aafee1d858a71ed69eb8c539aa9851796eb54b1af58f0bb97aba0
expect_hash Program/Magic.exe 685669692634ec830fe228904e11b1b536bd4b20e52192863a6280c2dbff6b66
expect_hash Shandalar.dll f74648745315163da15ffbe32e5bbdbc79e05aaf47c0714902c8d6898e5d00f7
expect_hash Program/Shandalar.dll f74648745315163da15ffbe32e5bbdbc79e05aaf47c0714902c8d6898e5d00f7
expect_hash CardArtLib.dll 975111a7f82d4e026a8572c669a678eddea2d5ffa895dce59f6416457e510484
expect_hash Program/CardArtLib.dll 975111a7f82d4e026a8572c669a678eddea2d5ffa895dce59f6416457e510484
expect_hash DeckDLL.dll 5c122ea5442d209d0d74c7e75f7b1f53492b0bfcc042efce49300f3485e3fcb0
expect_hash Program/Deckdll.dll 5c122ea5442d209d0d74c7e75f7b1f53492b0bfcc042efce49300f3485e3fcb0
expect_hash Drawcardlib.dll 9f37f131ba4a80ba543bb9372489438ac306cd01363b58cbc5ae8b1ccfd80700
expect_hash Program/Drawcardlib.dll 9f37f131ba4a80ba543bb9372489438ac306cd01363b58cbc5ae8b1ccfd80700
expect_hash Statwin.dll f1428cf548810f85df6f26b913d10dca16bc0f06a609a94c0cb0f0308347b0cf
expect_hash Program/Statwin.dll f1428cf548810f85df6f26b913d10dca16bc0f06a609a94c0cb0f0308347b0cf
expect_hash ManalinkEh.dll 68f2ba31f26f99edfb0944fe3fbc577ef0a42f9f6a6d7d44cb3aaa5f9b9cadd5
expect_hash Program/ManalinkEh.dll 619ce5d3f80f4ac951418e8a1b2ec803b3b9aa0128e01b827e744b80e63962fc
expect_hash zlib.dll 9f8729ac49e0ccea86fe3b1a9b2c3fae9986ecd09db92853e7a588dbda85bf90
expect_hash Program/zlib.dll 9f8729ac49e0ccea86fe3b1a9b2c3fae9986ecd09db92853e7a588dbda85bf90
expect_hash libgcc_s_dw2-1.dll 89f6147f5ed3f271d0b88f0586e079b9ac22e76c31221e5d5013aa273cc4694b
expect_hash Program/libgcc_s_dw2-1.dll 89f6147f5ed3f271d0b88f0586e079b9ac22e76c31221e5d5013aa273cc4694b
expect_hash Cards.dat abb2f631bd7897dcebde9d6c4bf61a6ea2e37e30fda42490c37b6f4d60f42e94
expect_hash Program/Cards.dat abb2f631bd7897dcebde9d6c4bf61a6ea2e37e30fda42490c37b6f4d60f42e94
expect_hash DBInfo.dat 519ccecb98548c1a2e15fe8025951aafba9f116595b5775a0f2ab2bb393e48c1
expect_hash Program/DBInfo.dat 519ccecb98548c1a2e15fe8025951aafba9f116595b5775a0f2ab2bb393e48c1
expect_hash Rarity.dat e0c779a73f0ed780b0c689741805a4e40f7f4949420a8d27fa73137e528ae04f
expect_hash Program/Rarity.dat e0c779a73f0ed780b0c689741805a4e40f7f4949420a8d27fa73137e528ae04f
expect_hash Program/Manalink.ini 30153fd22c76b0c0751c538938af46fbf25b1b51d5b4bb2bd9a2eead1b9c2f2b
expect_hash Program/DuelArt/Modern.dat 9a2d70be70b70ef27036a47550bc0d549437df0c032a4e0237a217e4731e1aee
expect_hash Program/DuelArt/Planeswalker.dat 619e0b9780ec204b9fbf6f48b2eb541c9d8a6f19a73f27d4d76d25828db7d369
expect_hash Program/TT0530m_.ttf 51afc07ba27699fec048dd387f6e6068177c0ee4cd95c6483eb378978fdd1cee
expect_hash Program/TT0127m_.ttf e3b5229e753851acab9450fcad1acd9f89412f7bdaebfb6fbf25fc0536ab02d2
expect_hash Program/TT0085m_.ttf e738818f4bbf3f29c68601fe5cb16cb045650e7d1854806e584204fd2686ed4c
expect_hash Program/TT0298m_.ttf a36d52dec6c6216e2dce6f0979c715e5454a0d18647bedd03096f33dbd3d707f
expect_hash Program/TT0299m_.ttf fb1ce5027aa0a0cd3817f559e63fe4d28b6e125c0c32d3635337d2acfb109519
expect_hash Program/TT0300m_.ttf 83a70d460edbdc1a804764d6b17de2189765a5eb18cf598e8fa7e88058d67a79
expect_hash Program/CardArt/ManaSymbols.pic 60662a25dce90dc8d4cd0b0227fe62c33b50ac95115711428d463770b8d42cbd
expect_hash Program/CardArt/Expansion_Symbols.pic 01264f3dd6b9a8b5576b50bba49e951cb3fbdba1d33aee2b7ee8a9530d5e7348
expect_hash Program/CardArt/Watermarks.pic ec276a27c79a8cea55cdcb5474cbc5b96071f3744c18d7fc466ea6c503892c9c
expect_hash Program/CardArt/CardCounters.png 8d26128c1932b22f25b84b96d8d01e9b2dce008cd96265f3efabdc0c5f11ecbb
expect_hash Program/CardArt/Modern/Triggering.png a8c94fc5b58540f884e799a1603f65dd61d99af9e50efee4762b4021bedc6f00
expect_hash Program/CardArt/Modern/CardOv_Nyx.png b4bbf12f1f9851e2526ba25ad9b3de147fafa6aa7b1bc4400616b65aaf25209d
expect_hash Program/CardArt/Planeswalker/LoyaltyBase.png 7413ba6227b9b07a491a2730e170525ea4744d188e31e2665abc2361ebd6e79e
expect_hash Program/CardArt/Planeswalker/LoyaltyMinus.png 89f01e1bda607459ea6560c0b6608a9aab409799c05cd00279fee6d0bfd82cb9
expect_hash Program/CardArt/Planeswalker/LoyaltyPlus.png ad4b8971dd43955ccfd3daf9020b3a6f60c0a8fe9f21b73847c07a81b12af3ef
expect_hash Program/CardArt/Planeswalker/LoyaltyZero.png 8faf7ec5225538bcb97b539a1614282007ea484317411806a311f1c2d800ccef
pass "patched runtime hashes match docs"

expect_pe_dll_characteristics Drawcardlib.dll 0000
expect_pe_dll_characteristics Program/Drawcardlib.dll 0000
pass "Drawcardlib PE startup flags are legacy-safe"

shandalar_land_cip_cave_hex=83fe017557833d00d28b0001744ef60534a99300027545813d78d19400db00000075393935381c8e0075313935b8f47b007529391dc42f8e0075218d149b89d0c1e00429d08d148752e842ed31ffa90100000074065fe90f0000005a8d149b8b0d381c8e00e9d38833ffc705ace97b0000000000ff3578d19400ff3564b7d106ff35b8f47b00ff35c42f8e00814f08000100106a006affba0100000029f25253566a7e5356e896c832ff83c4208b0424a3c42f8e008b442404a3b8f47b008b442408a364b7d1068b44240ca378d19400816708fffeffefc705ace97b000000000068000300005356e873972fff83c40c8f05c42f8e008f05b8f47b008f0564b7d1068f0578d19400e96d8a33ff
shandalar_player_target_cave_hex=898d3cfdffff837f08017515817f1400100000750c31c0a36cd49400e9fe052bffb8f8424c00ffd0a16cd49400e9d6052bff0000000000000000000000000000

expect_hex_prefix Shandalar.exe 0x1785b0 11 6a0057508b4d1051ff7504
expect_hex_prefix Program/Shandalar.exe 0x1785b0 11 6a0057508b4d1051ff7504
expect_hex_prefix Shandalar.exe 0xcda2e 5 9090909090
expect_hex_prefix Program/Shandalar.exe 0xcda2e 5 9090909090
expect_hex_prefix Shandalar.exe 0xcdccd 16 ff05f09d5800c2140090909090909090
expect_hex_prefix Program/Shandalar.exe 0xcdccd 16 ff05f09d5800c2140090909090909090
expect_hex_prefix Shandalar.exe 0xcdd3f 5 9090909090
expect_hex_prefix Program/Shandalar.exe 0xcdd3f 5 9090909090
expect_hex_prefix Shandalar.exe 0x16c320 6 b804000000c3
expect_hex_prefix Program/Shandalar.exe 0x16c320 6 b804000000c3
expect_hex_prefix Statwin.dll 0x2a10 6 b807000000c3
expect_hex_prefix Program/Statwin.dll 0x2a10 6 b807000000c3
expect_hex_prefix FaceMaker.exe 0x5f40 11 6a0057508b4d1051ff7504
expect_hex_prefix Program/FaceMaker.exe 0x5f40 11 6a0057508b4d1051ff7504
expect_hex_prefix Magic.exe 0x3c303 13 e9c0d801009090909090909090
expect_hex_prefix Program/Magic.exe 0x3c303 13 e9c0d801009090909090909090
expect_hex_prefix Magic.exe 0x59bc8 13 f74608040000000f8512000000
expect_hex_prefix Program/Magic.exe 0x59bc8 13 f74608040000000f8512000000
expect_hex_prefix Magic.exe 0x5db1f 10 c7055c72780000000000
expect_hex_prefix Program/Magic.exe 0x5db1f 10 c7055c72780000000000
expect_hex_prefix Magic.exe 0x694b7 16 6a0068ac5c71008b451050e8c9710000
expect_hex_prefix Program/Magic.exe 0x694b7 16 6a0068ac5c71008b451050e8c9710000
expect_hex_prefix Magic.exe 0x694eb 16 6a0068ac5c71008b451050e895710000
expect_hex_prefix Program/Magic.exe 0x694eb 16 6a0068ac5c71008b451050e895710000
expect_hex_prefix Shandalar.dll 0x94d34 9 e9c776cc0090909090
expect_hex_prefix Program/Shandalar.dll 0x94d34 9 e9c776cc0090909090
expect_hex_prefix Shandalar.dll 0x1174800 269 "$shandalar_land_cip_cave_hex"
expect_hex_prefix Program/Shandalar.dll 0x1174800 269 "$shandalar_land_cip_cave_hex"
expect_hex_prefix Shandalar.dll 0xcb16 18 e905fad40090909090909090909090909090
expect_hex_prefix Program/Shandalar.dll 0xcb16 18 e905fad40090909090909090909090909090
expect_hex_prefix Shandalar.dll 0x1174920 64 "$shandalar_player_target_cave_hex"
expect_hex_prefix Program/Shandalar.dll 0x1174920 64 "$shandalar_player_target_cave_hex"
expect_hex_prefix ManalinkEh.dll 0x3bb035 16 f60590f14e00040f84ae000000e90100
expect_hex_prefix Program/ManalinkEh.dll 0x381a25 16 f60590f14e00040f84ae000000e90100
expect_hex_prefix ManalinkEh.dll 0x1a8 4 00020000
expect_hex_prefix Program/ManalinkEh.dll 0x1a8 4 00020000
expect_hex_prefix ManalinkEh.dll 0x44cb23 5 e9089b0400
expect_hex_prefix Program/ManalinkEh.dll 0x40f115 5 e916450400
expect_hex_prefix ManalinkEh.dll 0x495a30 38 f7c30000000f7410f60590f14e0004750731d2e9d961fbfff6c3040f844265fbffe9d264fbff
expect_hex_prefix Program/ManalinkEh.dll 0x452c30 38 f7c30000000f7410f60590f14e0004750731d2e9d9b7fbfff6c3040f8434bbfbffe9c4bafbff
expect_hex_prefix ManalinkEh.dll 0x40d0e1 11 e97a950800909090909090
expect_hex_prefix Program/ManalinkEh.dll 0x3d2da1 11 e9ba080800909090909090
expect_hex_prefix ManalinkEh.dll 0x495a60 24 89c385c07e0881fb0e0100007e05bb0e010000e9746af7ff
expect_hex_prefix Program/ManalinkEh.dll 0x452c60 24 89c385c07e0881fb0e0100007e05bb0e010000e934f7f7ff
expect_hex_prefix ManalinkEh.dll 0x40db84 5 e9078b0800
expect_hex_prefix Program/ManalinkEh.dll 0x3d3844 5 e947fe0700
expect_hex_prefix ManalinkEh.dll 0x495a90 59 8d7db431c08b0c85c0f34e00890c874083f81075f0ba010000002b5508c1e20531c08b8c82a0f44e00898c82c0f34e004083f80875ece9eb74f7ff
expect_hex_prefix Program/ManalinkEh.dll 0x452c90 59 8d7db431c08b0c85c0f34e00890c874083f81075f0ba010000002b5508c1e20531c08b8c82a0f44e00898c82c0f34e004083f80875ece9ab01f8ff
expect_hex_prefix ManalinkEh.dll 0x429acf 10 e92ccc06009090909090
expect_hex_prefix Program/ManalinkEh.dll 0x3ec7cf 10 e92c6f06009090909090
expect_hex_prefix ManalinkEh.dll 0x3fe7a0 75 c744240c00000000b80100000029d88944240889742404891c24e881cd060085c00f84bfffffff89742404891c24e89dec0100c7442404010000008b4074890424e88aea0300e99bffffff
expect_hex_prefix Program/ManalinkEh.dll 0x3c4930 75 c744240c00000000b80100000029d88944240889742404891c24e8c16a060085c00f84bfffffff89742404891c24e80dd60100c7442404010000008b4074890424e80aaf0300e99bffffff
expect_hex_prefix ManalinkEh.dll 0x469583 17 e948d10200909090909090909090909090
expect_hex_prefix ManalinkEh.dll 0x495ad0 44 898d18fdffff817d1c00100000750d31d28915e42f7a00e9a82efdffe85f1f00fe8b15e42f7a00e9982efdff
expect_hex_prefix Program/ManalinkEh.dll 0x429453 17 e978a20200909090909090909090909090
expect_hex_prefix Program/ManalinkEh.dll 0x452cd0 44 898d18fdffff817d1c00100000750d31d28915e42f7a00e9785dfdffe85f4f04fe8b15e42f7a00e9685dfdff
expect_hex_prefix ManalinkEh.dll 0x3f63bd 5 e8ceed0300
expect_hex_prefix ManalinkEh.dll 0x3fe77d 5 e80e6a0300
expect_hex_prefix ManalinkEh.dll 0x495b00 247 83fb017542833d74857200017439813d782d7a00db000000752d391d1c7e73007525391d7cc16200751d3935209a730075156a015653e8d5c4f9ff83c40c85c07405e90f000000c705f8e9600000000000e98333f9ffc705f8e9600000000000ff35782d7a00ff35a4025902ff357cc16200ff35209a73005653e8f16cf8ff83c40889c7814f08000100106affba0100000029da526a7e5653e8122af9ff83c4148b0424a3209a73008b442404a37cc162008b442408a3a40259028b44240ca3782d7a00816708fffeffef68000300005653e8d9e7f9fd83c40c8f05209a73008f057cc162008f05a40259028f05782d7a00e94734f9ff
expect_hex_prefix Program/ManalinkEh.dll 0x3bc60d 5 e81ead0300
expect_hex_prefix Program/ManalinkEh.dll 0x3c490d 5 e81e2a0300
expect_hex_prefix Program/ManalinkEh.dll 0x452d00 247 83fb017542833d74857200017439813d782d7a00db000000752d391d1c7e73007525391d7cc16200751d3935209a730075156a015653e8251afaff83c40c85c07405e90f000000c705f8e9600000000000e98390f9ffc705f8e9600000000000ff35782d7a00ff3524055402ff357cc16200ff35209a73005653e8f1e7f8ff83c40889c7814f08000100106affba0100000029da526a7e5653e89289f9ff83c4148b0424a3209a73008b442404a37cc162008b442408a3240554028b44240ca3782d7a00816708fffeffef68000300005653e8d917fefd83c40c8f05209a73008f057cc162008f05240554028f05782d7a00e94791f9ff
pass "representative binary patch bytes match docs"

expect_text_match config.txt '^AiDecisionTime:270$'
expect_text_match Program/config.txt '^AiDecisionTime:270$'
expect_text_match Shandalar.ini '^AiDecisionTime[[:space:]]*=[[:space:]]*270$'
expect_text_match Program/Shandalar.ini '^AiDecisionTime[[:space:]]*=[[:space:]]*270$'
pass "AI decision-time config values are set to 270"

save_slot_count="$(git ls-files | awk '/^MAGIC[0-9a-d]\.(SVE|map|fce)$/ {count++} END {print count+0}')"
[ "$save_slot_count" = "33" ] || fail "expected 33 tracked root save slot/map/face files, found $save_slot_count"
save_export_count="$(git ls-files | awk '/^CSV\/MAGIC[3-6]\// {count++} END {print count+0}')"
[ "$save_export_count" = "32" ] || fail "expected 32 tracked CSV save exports, found $save_export_count"
for path in \
  MAGIC5 \
  Savedescs \
  Program/Savedescs \
  FaceMostRecent.txt \
  Screennames/Activename.dat \
  Screennames/CirothUngol.scn \
  Screennames/Player.scn \
  Manalink3/Program/ScreenNames/ActiveName.dat \
  Manalink3/Program/ScreenNames/CirothUngol.scn
do
  expect_tracked_file "$path"
done
pass "tracked save/local-state inventory matches docs"

expect_file tools/list-security-scan-targets.sh
[ -x tools/list-security-scan-targets.sh ] || fail "tools/list-security-scan-targets.sh is not executable"
security_targets="$(tools/list-security-scan-targets.sh)"
security_header="$(printf '%s\n' "$security_targets" | sed -n '1p')"
[ "$security_header" = $'path\tkind\tbytes\tsha256' ] || fail "unexpected security target header: $security_header"
security_target_count="$(printf '%s\n' "$security_targets" | awk 'NR > 1 {count++} END {print count+0}')"
[ "$security_target_count" -ge "200" ] || fail "expected at least 200 tracked security scan targets, found $security_target_count"
for path in \
  Shandalar.exe \
  Program/Magic.exe \
  ManalinkEh.dll \
  Program/ManalinkEh.dll \
  Mods/Util/7za.exe \
  DeckInjector.jar \
  "Shandalar help.bat" \
  tools/create-cleanup-test-copy.sh \
  tools/create-git-handoff-bundle.sh \
  tools/create-patch-package.sh \
  tools/create-security-scan-results-template.sh \
  tools/check-security-scanner-availability.sh \
  tools/list-branch-delta.sh \
  tools/print-manual-gameplay-baseline.sh \
  tools/print-security-scan-baseline.sh \
  tools/print-share-status.sh \
  tools/record-manual-gameplay-result.sh \
  tools/record-security-scan-result.sh \
  tools/verify-final-share-gates.sh \
  tools/verify-handoff-artifacts.sh \
  tools/verify-handoff-readiness.sh \
  tools/verify-share-readiness.sh \
  tools/verify-install-tree.sh \
  tools/verify-manual-gameplay-results.sh \
  tools/verify-security-scan-results.sh \
  tools/verify-crossover-mtg-state.sh \
  tools/list-security-scan-targets.sh
do
  printf '%s\n' "$security_targets" | awk -F '\t' -v p="$path" 'NR > 1 && $1 == p {found=1} END {exit found ? 0 : 1}' || fail "security scan target inventory is missing $path"
done
pass "security scan target inventory is generated ($security_target_count checked)"

expect_file tools/list-branch-delta.sh
[ -x tools/list-branch-delta.sh ] || fail "tools/list-branch-delta.sh is not executable"
branch_delta="$(tools/list-branch-delta.sh)"
branch_delta_header="$(printf '%s\n' "$branch_delta" | sed -n '1p')"
[ "$branch_delta_header" = $'status\tpath\told_path\tkind\tbytes\tsha256' ] || fail "unexpected branch-delta header: $branch_delta_header"
branch_delta_count="$(printf '%s\n' "$branch_delta" | awk 'NR > 1 {count++} END {print count+0}')"
on_base_branch=0
if [ "$(git rev-parse HEAD)" = "$(git rev-parse master)" ]; then
  on_base_branch=1
fi
if [ "$on_base_branch" = "1" ]; then
  [ "$branch_delta_count" = "0" ] || fail "expected no branch-delta rows on master, found $branch_delta_count"
else
  [ "$branch_delta_count" -gt "0" ] || fail "expected branch-delta rows on maintenance branch, found $branch_delta_count"
fi
branch_delta_other_count="$(printf '%s\n' "$branch_delta" | awk -F '\t' 'NR > 1 && $4 == "other" {count++} END {print count+0}')"
[ "$branch_delta_other_count" = "0" ] || fail "branch-delta inventory has $branch_delta_other_count rows classified as other"
branch_delta_summary="$(tools/list-branch-delta.sh --summary)"
printf '%s\n' "$branch_delta_summary" | grep -q "# Branch Delta Summary" || fail "branch-delta summary missing heading"
printf '%s\n' "$branch_delta_summary" | grep -q "| Changed paths | $branch_delta_count |" || fail "branch-delta summary does not report $branch_delta_count changed paths"
if [ "$on_base_branch" = "1" ]; then
  pass "branch-delta inventory is empty on master"
else
  for expected in \
    $'AGENTS.md\tdocumentation' \
    $'DeckDLL.dll\tpe-dll' \
    $'ManalinkEh.dll\tpe-dll' \
    $'Program/Statwin.dll\tpe-dll' \
    $'Program/Deckdll.dll\tpe-dll' \
    $'Program/ManalinkEh.dll\tpe-dll' \
    $'Program/Shandalar.exe\tpe-executable' \
    $'Program/src/cards/worldwake.c\tsource' \
    $'Program/src/cards/zendikar.c\tsource' \
    $'Program/src/functions/targets.c\tsource' \
    $'Shandalar.exe\tpe-executable' \
    $'Statwin.dll\tpe-dll' \
    $'docs/bugs/ai-etb-player-target-spell-chain-freeze.md\tdocumentation' \
    $'docs/bugs/piranha-marsh-spell-chain-freeze.md\tdocumentation' \
    $'docs/manual-gameplay-verification.md\tdocumentation' \
    $'docs/runtime-manifest.md\tdocumentation' \
    $'src/cards/worldwake.c\tsource' \
    $'src/cards/zendikar.c\tsource' \
    $'src/functions/targets.c\tsource' \
    $'tools/check-source-snapshot-parity.sh\tshell-tool' \
    $'tools/patch-ai-etb-player-target-preselect.py\tpython-tool' \
    $'tools/patch-statwin-disable-magvid-loader.py\tpython-tool' \
    $'tools/patch-shandalar-disable-magsnd-init.py\tpython-tool' \
    $'tools/patch-shandalar-magsnd-update-callback.py\tpython-tool' \
    $'tools/patch-shandalar-winmm-tick-callback.py\tpython-tool' \
    $'tools/verify-crossover-mtg-state.sh\tshell-tool' \
    $'tools/verify-install-tree.sh\tshell-tool' \
    $'tools/verify-share-readiness.sh\tshell-tool'
  do
    path="${expected%$'\t'*}"
    kind="${expected#*$'\t'}"
    printf '%s\n' "$branch_delta" | awk -F '\t' -v p="$path" -v k="$kind" 'NR > 1 && $2 == p && $4 == k {found=1} END {exit found ? 0 : 1}' || fail "branch-delta inventory is missing $path as $kind"
  done
  pass "branch-delta inventory is reviewable ($branch_delta_count checked)"
fi

patch_dry_run="$(tools/create-patch-package.sh --dry-run --skip-verify --dest /private/tmp/shandalar-patch-package-dryrun.patch)"
printf '%s\n' "$patch_dry_run" | grep -q "Receiver checksum command" || fail "patch dry-run missing receiver checksum command"
printf '%s\n' "$patch_dry_run" | grep -q "Receiver check command" || fail "patch dry-run missing receiver check command"
printf '%s\n' "$patch_dry_run" | grep -q "Receiver apply command" || fail "patch dry-run missing receiver apply command"
pass "patch package dry-run passed"

for path in \
  README.md \
  AGENTS.md \
  docs/README.md \
  docs/branch-summary.md \
  docs/completion-audit.md \
  docs/git-handoff.md \
  docs/push-auth.md \
  docs/release-scope.md \
  docs/share-readiness.md \
  docs/distribution.md \
  docs/patch-package-plan.md \
  docs/verified-on-this-machine.md \
  docs/runtime-manifest.md \
  docs/manual-gameplay-verification.md \
  docs/runtime-testing-policy.md \
  docs/runtime-test-notes.md \
  docs/cleanup-audit.md \
  docs/cleanup-removed-files.md \
  docs/repo-cleanup-plan.md \
  docs/cleanup-launch-copy-test.md \
  docs/duplicate-audit.md \
  docs/cleanup-move-plan.md \
  docs/save-state.md \
  docs/runtime-dependencies.md \
  docs/security-scan.md
do
  expect_file "$path"
done
pass "core docs exist"

grep -F -q 'app-default `win7`, desktop `Shandalar1440=1440x1080`' README.md || fail "README is missing the current MTG CrossOver win7/Shandalar1440 guidance"
grep -F -q '`Shandalar-Win8-Test` bottle is comparison evidence, not the primary path.' README.md || fail "README does not identify Shandalar-Win8-Test as comparison evidence"
pass "top-level CrossOver guidance is current"

grep -F -q 'This repo work is not primarily a Wine/CrossOver GUI-automation task.' docs/runtime-testing-policy.md || fail "runtime testing policy is missing the core rule"
grep -F -q 'Stop GUI testing immediately' docs/runtime-testing-policy.md || fail "runtime testing policy is missing stop conditions"
grep -F -q 'docs/runtime-testing-policy.md' AGENTS.md || fail "AGENTS.md does not reference runtime testing policy"
grep -F -q 'runtime-testing-policy.md' local/README.md || fail "local helper docs do not reference runtime testing policy"
grep -F -q 'runtime-testing-policy.md' README.md || fail "README does not reference runtime testing policy"
pass "runtime testing policy is documented and indexed"

python3 - <<'PY'
from pathlib import Path
import hashlib
import re
import sys

manifest = Path("docs/runtime-manifest.md")
row_re = re.compile(r"^\|\s*`([^`]+)`\s*\|\s*`([0-9a-f]{64})`\s*\|")
checked = 0
failures = []

for line in manifest.read_text(encoding="utf-8").splitlines():
    match = row_re.match(line)
    if not match:
        continue

    rel_path, expected = match.groups()
    path = Path(rel_path)
    checked += 1

    if not path.is_file():
        failures.append(f"missing manifest file: {rel_path}")
        continue

    actual = hashlib.sha256(path.read_bytes()).hexdigest()
    if actual != expected:
        failures.append(f"{rel_path} sha256 {actual} != {expected}")

if checked == 0:
    failures.append("runtime manifest contains no SHA-256 rows")

if failures:
    for failure in failures:
        print(f"manifest mismatch: {failure}", file=sys.stderr)
    sys.exit(1)

print(f"ok: runtime manifest hashes match current files ({checked} checked)")
PY

python3 - <<'PY'
from pathlib import Path
import sys

checked = 0
violations = []
allowed_suffixes = {".md", ".sh", ".vbs"}

for path in sorted(Path(".").rglob("*")):
    if ".git" in path.parts or path.parts[:2] == ("docs", "generated"):
        continue
    if not path.is_file() or path.suffix.lower() not in allowed_suffixes:
        continue

    checked += 1
    data = path.read_bytes()
    for line_no, line in enumerate(data.splitlines(), start=1):
        if any(byte > 0x7F for byte in line):
            violations.append((path, line_no))
            break

if violations:
    for path, line_no in violations:
        print(f"non-ASCII text: {path}:{line_no}", file=sys.stderr)
    sys.exit(1)

print(f"ok: maintained text files are ASCII ({checked} checked)")
PY

python3 - <<'PY'
from pathlib import Path
import sys

index_paths = [
    Path("README.md"),
    Path("docs/README.md"),
    Path("docs/share-readiness.md"),
    Path("docs/branch-summary.md"),
]
index_text = "\n".join(path.read_text(encoding="utf-8") for path in index_paths)

docs = [
    Path("AGENTS.md"),
    Path("archive/README.md"),
    Path("local/README.md"),
    Path("tools/README.md"),
]

for path in sorted(Path("docs").rglob("*.md")):
    if path.parts[:2] == ("docs", "generated") and path != Path("docs/generated/README.md"):
        continue
    docs.append(path)

missing = []
for path in docs:
    aliases = {path.as_posix()}
    if path.parts[0] == "docs":
        aliases.add(path.relative_to("docs").as_posix())

    if not any(alias in index_text for alias in aliases):
        missing.append(path.as_posix())

if missing:
    for path in missing:
        print(f"doc is not indexed: {path}", file=sys.stderr)
    sys.exit(1)

print(f"ok: maintained docs are indexed ({len(docs)} checked)")
PY

python3 - <<'PY'
from pathlib import Path
import re
import sys
import urllib.parse

root = Path(".")
link_re = re.compile(r"(?<!!)\[[^\]]+\]\(([^)]+)\)")
missing = []
checked = 0

for md in sorted(path for path in root.rglob("*.md") if ".git" not in path.parts):
    text = md.read_text(encoding="utf-8", errors="replace")
    for match in link_re.finditer(text):
        raw = match.group(1).strip()
        if not raw or raw.startswith(("#", "http://", "https://", "mailto:", "file:", "vscode:")):
            continue
        target = raw.split("#", 1)[0]
        if not target:
            continue
        if target.startswith("<") and target.endswith(">"):
            target = target[1:-1]
        target = urllib.parse.unquote(target)
        if re.match(r"^[A-Za-z]:[\\/]", target):
            continue

        checked += 1
        resolved = (md.parent / target).resolve()
        if not resolved.exists():
            line = text[:match.start()].count("\n") + 1
            missing.append((md, line, raw))

if missing:
    for md, line, raw in missing:
        print(f"missing markdown link: {md}:{line}: {raw}", file=sys.stderr)
    sys.exit(1)

print(f"ok: local Markdown links resolve ({checked} checked)")
PY

printf 'Share-readiness automated checks passed.\n'
